### ISSUE TITLE
Change component for "Description" Citation metadata field

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#976] opened 2020-05-07 08:08 UTC
Currently the field ignores even new lines and users having no knowledge of HTML will have problems with formatting descriptions. 

Let's change the component to this one: https://www.primefaces.org/showcase/ui/input/textEditor.xhtml

We should limit the possible options (buttons etc.) to HTML tags that we currently support. 

If there are some tags that are not supported by the component, we should stop supporting them.

**Comment by madryk** [comment] 2020-07-07 11:39
duplicate of #987

**Closed as completed by madryk** 2020-07-07 11:39 UTC
